import{a as k,i as d,S as E,N as S,K as B}from"./assets/vendor-DD6Zhatt.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=n(t);fetch(t.href,s)}})();async function I(){return(await k("https://portfolio-js.b.goit.study/api/reviews")).data}const f=document.getElementById("theme-toggle"),u=document.body;localStorage.getItem("theme")==="dark"&&(u.classList.add("dark-mode"),f.checked=!0);function O(){f.checked?(u.classList.add("dark-mode"),localStorage.setItem("theme","dark")):(u.classList.remove("dark-mode"),localStorage.setItem("theme","light"))}f.addEventListener("change",O);const q=document.querySelector(".burger-btn"),a=document.querySelector(".modal-overlay"),M=document.querySelector(".modal-btn");q.addEventListener("click",()=>{a.classList.add("active"),document.body.style.overflow="hidden"});function g(){a.classList.remove("active"),document.body.style.overflow=""}M.addEventListener("click",g);a.addEventListener("click",e=>{e.target===a&&g()});document.addEventListener("keydown",e=>{e.key==="Escape"&&a.classList.contains("active")&&g()});const b=document.querySelector(".swiper-wrapper"),m=document.querySelector(".section-reviews");let p=null,h=!1,L=!1,v=!1;const w=document.createDocumentFragment();x();async function x(){try{p=await I()}catch{L=!0}finally{R.observe(m)}}function C(e){e.forEach(({_id:o,author:n,avatar_url:r,review:t})=>{const s=`
      <li class="swiper-slide" data-id="${o}">
        <p class="reviews-item-text">${t}</p>
        <div class="container-reviews-author">
          <img class="reviews-item-img" src="${r}" alt="${n}"/>
          <h3 class="reviews-item-name">${n}</h3>
        </div>
      </li>
      `,i=document.createElement("div");i.insertAdjacentHTML("beforeend",s),w.append(...i.children)}),b.append(w)}function N(){new E(".swiper",{modules:[S,B],navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},spaceBetween:32,slidesPerView:1,slidesPerGroup:1,autoHeight:!0,breakpoints:{1280:{slidesPerView:2,spaceBetween:32}},keyboard:{enabled:!0,onlyInViewport:!0}})}const P={root:null,rootMargin:"1000px",threshold:0},R=new IntersectionObserver(T,P);function T(e,o){e.forEach(n=>{n.isIntersecting&&(p&&!h&&(h=!0,o.unobserve(m),C(p),N()),L&&!v&&(v=!0,o.unobserve(m),D()))})}function D(){d.info({title:"Info",message:"Reviews not found!",position:"topRight",backgroundColor:"beige"}),b.innerHTML=`
    <li class="swiper-slide">
    <h3 class="title-error">
      Oops! Looks like the reviews didn’t load. We’re working on it — please check back shortly!
    </h3>
    </li>`;const e=document.querySelector(".swiper-button-prev"),o=document.querySelector(".swiper-button-next");e.disabled=!0,o.disabled=!0,e.style.opacity=.3,o.style.opacity=.3,document.querySelector(".swiper-slide").style.maxWidth="100%"}const l=document.getElementById("contact-form"),c=document.getElementById("success-modal"),$=document.querySelector(".close-modal");l.addEventListener("submit",async function(e){e.preventDefault();const o=l.elements["form-email"].value.trim(),n=l.elements["user-message"].value.trim();try{(await fetch("https://portfolio-js.b.goit.study/api/requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:o,comment:n})})).ok?(F(),l.reset()):d.warning({title:"Warning",message:"Check the data and try again",position:"topRight",backgroundColor:"#FFB81C",messageColor:"#3B3D40",timeout:5e3,progressBar:!1,close:!0,maxWidth:400,transitionIn:"fadeInDown",transitionOut:"fadeOutUp"})}catch{d.warning({title:"Network error",message:"Try again.",position:"topRight",backgroundColor:"#FFB81C",messageColor:"#3B3D40",timeout:5e3,progressBar:!1,close:!0,transitionIn:"fadeInDown",transitionOut:"fadeOutUp"})}});function F(){c.classList.add("is-open"),document.body.classList.add("modal-open")}function y(){c.classList.remove("is-open"),document.body.classList.remove("modal-open")}$.addEventListener("click",y);c.addEventListener("click",function(e){e.target===c&&y()});document.addEventListener("keydown",function(e){e.key==="Escape"&&c.classList.contains("is-open")&&y()});
//# sourceMappingURL=index.js.map
