import{a as k,A as S,i as u,S as E,N as I,K as O}from"./assets/vendor-BgWgrTJC.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function s(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(o){if(o.ep)return;o.ep=!0;const n=s(o);fetch(o.href,n)}})();async function B(){return(await k("https://portfolio-js.b.goit.study/api/reviews")).data}const g=document.getElementById("theme-toggle"),m=document.body;localStorage.getItem("theme")==="dark"&&(m.classList.add("dark-mode"),g.checked=!0);function C(){g.checked?(m.classList.add("dark-mode"),localStorage.setItem("theme","dark")):(m.classList.remove("dark-mode"),localStorage.setItem("theme","light"))}g.addEventListener("change",C);const M=document.querySelector(".burger-btn"),c=document.querySelector(".modal-overlay"),$=document.querySelector(".modal-btn");M.addEventListener("click",()=>{c.classList.add("active"),document.body.style.overflow="hidden"});function y(){c.classList.remove("active"),document.body.style.overflow=""}$.addEventListener("click",y);c.addEventListener("click",e=>{e.target===c&&y()});document.addEventListener("keydown",e=>{e.key==="Escape"&&c.classList.contains("active")&&y()});const d="/js-team-17/assets/sprite-Ci5rsj_u.svg";new S(".faq-list",{duration:150,showOne:!0,openOnInit:[0],onOpen:function(e){document.querySelectorAll(".faq-item").forEach(function(r){r.classList.remove("ac-active");const o=r.querySelector(".faq-btn-accordion use");o&&o.setAttribute("href",`${d}#icon-faq-down`)});const s=e.closest(".faq-item");if(s){s.classList.add("ac-active");const r=s.querySelector(".faq-btn-accordion use");r&&r.setAttribute("href",`${d}#icon-faq-up`)}},onClose:function(e){const t=e.closest(".faq-item");if(t){t.classList.remove("ac-active");const s=t.querySelector(".faq-btn-accordion use");s&&s.setAttribute("href",`${d}#icon-faq-down`)}}});const A=document.querySelectorAll(".faq-item");A.forEach(function(e){const t=e.querySelector(".faq-btn-accordion use");t&&t.setAttribute("href",`${d}#icon-faq-down`)});const L=document.querySelector(".swiper-wrapper"),f=document.querySelector(".section-reviews");let p=null,h=!1,q=!1,w=!1;const b=document.createDocumentFragment();x();async function x(){try{p=await B()}catch{q=!0}finally{T.observe(f)}}function N(e){e.forEach(({_id:t,author:s,avatar_url:r,review:o})=>{const n=`
      <li class="swiper-slide" data-id="${t}">
        <p class="reviews-item-text">${o}</p>
        <div class="container-reviews-author">
          <img class="reviews-item-img" src="${r}" alt="${s}"/>
          <h3 class="reviews-item-name">${s}</h3>
        </div>
      </li>
      `,i=document.createElement("div");i.insertAdjacentHTML("beforeend",n),b.append(...i.children)}),L.append(b)}function P(){new E(".swiper",{modules:[I,O],navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},spaceBetween:32,slidesPerView:1,slidesPerGroup:1,autoHeight:!0,breakpoints:{1280:{slidesPerView:2,spaceBetween:32}},keyboard:{enabled:!0,onlyInViewport:!0}})}const R={root:null,rootMargin:"1000px",threshold:0},T=new IntersectionObserver(D,R);function D(e,t){e.forEach(s=>{s.isIntersecting&&(p&&!h&&(h=!0,t.unobserve(f),N(p),P()),q&&!w&&(w=!0,t.unobserve(f),U()))})}function U(){u.info({title:"Info",message:"Reviews not found!",position:"topRight",backgroundColor:"beige"}),L.innerHTML=`
    <li class="swiper-slide">
    <h3 class="title-error">
      Oops! Looks like the reviews didn’t load. We’re working on it — please check back shortly!
    </h3>
    </li>`;const e=document.querySelector(".swiper-button-prev"),t=document.querySelector(".swiper-button-next");e.disabled=!0,t.disabled=!0,e.style.opacity=.3,t.style.opacity=.3,document.querySelector(".swiper-slide").style.maxWidth="100%"}const l=document.getElementById("contact-form"),a=document.getElementById("success-modal"),j=document.querySelector(".close-modal");l.addEventListener("submit",async function(e){e.preventDefault();const t=l.elements["form-email"].value.trim(),s=l.elements["user-message"].value.trim();try{(await fetch("https://portfolio-js.b.goit.study/api/requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:t,comment:s})})).ok?(F(),l.reset()):u.warning({title:"Warning",message:"Check the data and try again",position:"topRight",backgroundColor:"#FFB81C",messageColor:"#3B3D40",timeout:5e3,progressBar:!1,close:!0,maxWidth:400,transitionIn:"fadeInDown",transitionOut:"fadeOutUp"})}catch{u.warning({title:"Network error",message:"Try again.",position:"topRight",backgroundColor:"#FFB81C",messageColor:"#3B3D40",timeout:5e3,progressBar:!1,close:!0,transitionIn:"fadeInDown",transitionOut:"fadeOutUp"})}});function F(){a.classList.add("is-open"),document.body.classList.add("modal-open")}function v(){a.classList.remove("is-open"),document.body.classList.remove("modal-open")}j.addEventListener("click",v);a.addEventListener("click",function(e){e.target===a&&v()});document.addEventListener("keydown",function(e){e.key==="Escape"&&a.classList.contains("is-open")&&v()});
//# sourceMappingURL=index.js.map
